server:
  port: 8001

spring:
  application:
    name: distributed-inventory-system
  
  datasource:
    url: jdbc:sqlite:inventory.db
    driver-class-name: org.sqlite.JDBC
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
        id:
          new_generator_mappings: false
    generate-ddl: true
        
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

# Actuator for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# API Documentation
springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger-ui.html

# Resilience4j Configuration  
resilience4j:
  circuitbreaker:
    instances:
      inventory-service:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        minimumNumberOfCalls: 5
  retry:
    instances:
      inventory-service:
        maxAttempts: 3
        waitDuration: 1s
        exponentialBackoffMultiplier: 2

# Logging
logging:
  level:
    com.inventory: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG